### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by mathiasstocker** [symfony/notifier#2]
Is there a reason why the documention linked in the README is not available anymore?
https://symfony.com/doc/current/components/notifier.html

I found https://symfony.com/components/Notifier but it is not really helpful ...

**Comment by Armanho** [comment]
Please state your issue in the [main Symfony repository](https://github.com/symfony/symfony).

**Comment by nicolas-grekas** [comment]
Would you mind send a PR on the main repo to fix this? I'm surprised by the number of upvotes on this issue while nobody submitted one actually. Don't be shy people :)
